# Generated by Django 3.1 on 2021-03-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rstapp', '0002_dates'),
    ]

    operations = [
        migrations.CreateModel(
            name='threshold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(blank=True, default=None, null=True)),
            ],
        ),
    ]
