# Generated by Django 3.1 on 2021-04-14 19:40

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rstapp', '0003_threshold'),
    ]

    operations = [
        migrations.CreateModel(
            name='last_outputs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('args', picklefield.fields.PickledObjectField(editable=False)),
            ],
        ),
    ]
