# Generated by Django 3.1 on 2021-04-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rstapp', '0004_last_outputs'),
    ]

    operations = [
        migrations.AddField(
            model_name='dates',
            name='filename',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
