# Generated by Django 3.2.2 on 2021-05-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rstapp', '0005_dates_filename'),
    ]

    operations = [
        migrations.CreateModel(
            name='github',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='dates',
            name='filename',
        ),
    ]
